runtime: nodejs10
# env: flex

# handlers:
#   - url: /
#     static_files:build/index.html
#     upload: build/index.html

beta_settings:
cloud_sql_instances: urban-vogue:us-central1:urban-vogue-0001

